version: '3.1'

services:
  web:
    image: odoo:8.0
    depends_on:
      - db
    ports:
      - "8008:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom_addons/add:/mnt/extra-addons/add
      
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  db:
    image: postgres:9.3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
      

volumes:
  odoo-data:
  odoo-db-data:
